version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user_flask
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_flask
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user_flask:password123@db:5432/db_flask

volumes:
  postgres_data:
